Repository zilliztech/milvus-helm, pull requests merged in 2023-10, with the labels that each got.

#23 [Milvus] Add labels to attu component
  charts/milvus/Chart.yaml
  charts/milvus/templates/attu-deployment.yaml
Labels: approved, ci-passed, lgtm, size/XS

#26 [Milvus] Add nodeSelector to Attu deployment
  charts/milvus/Chart.yaml
  charts/milvus/templates/attu-deployment.yaml
Labels: approved, ci-passed, lgtm, size/S

#13 [milvus] S3 miss the region/useVirtualHost settings
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#19 [milvus] allow to unset replicas field in autoscalable deployments
  charts/milvus/Chart.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#27 tune mergify's rules
  .github/mergify.yml
  .github/workflows/checks.yaml
  .github/workflows/lint-test.yml
Labels: approved, ci-passed, lgtm, size/M

#29 Refine etcd probe timeout
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#32 Bump milvus version to v2.3.2
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#33 Remove mysql as metastore
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/charts/mysql-8.5.3.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/L
