Repository zilliztech/milvus-helm, pull requests merged in 2023-08, with the labels that each got.

#1 [milvus] Add podLabels option for attu.
  charts/milvus/Chart.yaml
  charts/milvus/templates/attu-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm

#4 Refine doc link
  .github/workflows/lint-test.yml
  .github/workflows/release.yml
  README.md
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
Labels: approved, ci-passed, lgtm

#5 Add new message queue natsmq for milvus standalone
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/M

#7 Bump milvus version to 2.2.14
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS
