Repository zilliztech/milvus-helm, pull requests merged in 2023-11, with the labels that each got.

#35 Bump milvus version to v2.3.3
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#25 [milvus] 22 proxy tls support
  charts/milvus/README.md
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/proxy-tls-secret.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/M

#40 [milvus] 2.3.3 config common.storageType: remote to support azure
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
Labels: approved, ci-passed, lgtm, size/XS
