Repository zilliztech/milvus-helm, pull requests merged in 2024-11, with the labels that each got.

#138 [milvus] Support custom annotations in pod deployments
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/M

#139 bump milvus to 2.4.15
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#141 doc: Affinity, Tolerations and Node Selector
  charts/milvus/README.md
  docs/affinity-configuration-guide.md
  docs/node-selector-configuration-guide.md
  docs/node-selectors-vs-node-affinity.md
  docs/tolerations-configuration-guide.md
Labels: approved, lgtm, size/XL

#143 doc: update link
  charts/milvus/README.md
Labels: approved, ci-passed, lgtm, size/XS

#146 release tag 2.4.16
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#144 support pulsar v3, update helm & kubernetes' minimum version
  .github/workflows/lint-test.yml
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/charts/pulsar-3.3.0.tgz
  charts/milvus/ci/cluster-values.yaml
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/L

#147 update readme for 4.2.21+ Compatibility Notice
  README.md
  charts/milvus/Chart.yaml
  charts/milvus/README.md
Labels: approved, ci-passed, lgtm, size/M

#148 add pulsar chart alias, add some default values for pulsar3
  charts/milvus/Chart.yaml
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#149 release tag 2.4.17
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#152 release tag 2.5.0-beta
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#153 enable pulsarv3 & disable pulsarv2 by default
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#159 Fix pulsar v2 and v3 chart incompatibility
  charts/milvus/Chart.yaml
  charts/milvus/charts/pulsar-2.7.8.tgz
  charts/milvus/charts/pulsarv2-2.7.8.tgz
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
Labels: approved, ci-passed, lgtm, size/S

#160 Fix pulsar values
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#158 change dep pulsar to zilliz pulsarv2 chart
  README.md
  charts/milvus/Chart.yaml
  charts/milvus/README.md
Labels: approved, ci-passed, lgtm, size/XS
