Repository zilliztech/milvus-helm, pull requests merged in 2024-07, with the labels that each got.

#97 [milvus] Ability to use user specified ConfigMap for Milvus configuration
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/configmap.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/L

#105 Update approvers & reviewers in OWNERS file
  OWNERS
Labels: approved, ci-passed, lgtm, size/XS

#108 Bump milvus version to v2.4.6
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/L

#72 add namespace metadata
  charts/milvus/templates/attu-deployment.yaml
  charts/milvus/templates/attu-ingress.yaml
  charts/milvus/templates/attu-svc.yaml
  charts/milvus/templates/configmap.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datacoord-svc.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/datanode-svc.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexcoord-svc.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/indexnode-svc.yaml
  charts/milvus/templates/ingress.yaml
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/mixcoord-svc.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/proxy-tls-secret.yaml
  charts/milvus/templates/pulsar-podmonitor.yaml
  charts/milvus/templates/pvc.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querycoord-svc.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/querynode-svc.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/rootcoord-svc.yaml
  charts/milvus/templates/service.yaml
  charts/milvus/templates/serviceaccount.yaml
  charts/milvus/templates/servicemonitor.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/minio/templates/configmap.yaml
  charts/minio/templates/deployment.yaml
  charts/minio/templates/ingress.yaml
  charts/minio/templates/networkpolicy.yaml
  charts/minio/templates/poddisruptionbudget.yaml
  charts/minio/templates/podmonitor.yaml
  charts/minio/templates/post-install-create-bucket-job.yaml
  charts/minio/templates/post-install-prometheus-metrics-job.yaml
  charts/minio/templates/post-install-prometheus-metrics-role.yaml
  charts/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
  charts/minio/templates/post-install-prometheus-metrics-serviceaccount.yaml
  charts/minio/templates/pvc.yaml
  charts/minio/templates/secrets.yaml
  charts/minio/templates/securitycontextconstraints.yaml
  charts/minio/templates/service.yaml
  charts/minio/templates/statefulset.yaml
Labels: approved, ci-passed, lgtm, size/M

#104 Fix template helper file
  charts/milvus/templates/_helpers.tpl
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#109 feat: add ingressClass
  charts/milvus/Chart.yaml
  charts/milvus/templates/attu-ingress.yaml
  charts/milvus/templates/ingress.yaml
  charts/milvus/values.yaml
Labels: enhancement, approved, ci-passed, lgtm, size/S

#110 chore: Compatibility Notice
  charts/milvus/README.md
Labels: approved, ci-passed, lgtm, size/XS
