Repository zilliztech/milvus-helm, pull requests merged in 2024-05, with the labels that each got.

#87 bump milvus version to v2.4.1
  .github/workflows/lint-test.yml
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/requirements.lock
  charts/milvus/requirements.yaml
  charts/milvus/values.yaml
  ct.yaml
Labels: approved, ci-passed, lgtm, size/S

#88 Fix release chart action
  .github/workflows/release.yml
Labels: approved, ci-passed, size/XS

#89 [milvus-4.1.31] Enhanced Attu Component
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#91 bump milvus version to v2.4.3
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#96 bump milvus version to v2.4.4
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS
