Repository zilliztech/milvus-helm, pull requests merged in 2024-08, with the labels that each got.

#112 Fix external s3 config
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
Labels: approved, ci-passed, lgtm, size/S

#113 update attu version to 2.4.6
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#114 Bump to 2.4.7
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/config.tpl
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#115 Use mixcoord for milvus cluster by default
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/M

#118 bump milvus to 2.4.9
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#119 [milvus] bump attu version to v2.4.7
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#122 bump milvus to 2.4.10
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS
