Repository zilliztech/milvus-helm, pull requests merged in 2024-01, with the labels that each got.

#47 [milvus] <docs>: Add docs for the minimal standalone
  .github/workflows/lint-test.yml
  charts/milvus/README.md
Labels: approved, ci-passed, lgtm, size/M

#48 [Milvus] <docs>: add more comments to externalKafka parameter
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#49 [Milvus] <readme>: update minio readme reference link in milvus value file
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#50 Bump milvus version to v2.3.5
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#51 update etcd image to support arm
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#53 Bump milvus version to v2.3.6
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#54 Reset milvus version to v2.3.5
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#55 Bump milvus version to v2.3.7
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS
