Repository zilliztech/milvus-helm, pull requests merged in 2025-02, with the labels that each got.

#177 change liveness probe to tcpSocket
  charts/milvus/Chart.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/templates/streamingnode-deployment.yaml
Labels: approved, ci-passed, lgtm, size/M

#182 update attu version to 2.5.3
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#183 fix doc
  charts/milvus/README.md
Labels: approved, ci-passed, lgtm, size/S

#186 release tag 2.5.5
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S
