Repository zilliztech/milvus-helm, pull requests merged in 2025-03, with the labels that each got.

#189 release tag 2.5.6
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#191 feat: add tei
  charts/milvus/README-TEI.md
  charts/milvus/README.md
  charts/milvus/templates/tei-headless-service.yaml
  charts/milvus/templates/tei-service.yaml
  charts/milvus/templates/tei-statefulset.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/L

#190 [milvus] Added memory threshold for query node hpa and unified default settings for templates and README
  charts/milvus/README.md
  charts/milvus/templates/datanode-hpa.yaml
  charts/milvus/templates/indexnode-hpa.yaml
  charts/milvus/templates/proxy-hpa.yaml
  charts/milvus/templates/querynode-hpa.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S

#194 release tag 2.5.7
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#199 add tei chart
  charts/tei/.helmignore
  charts/tei/Chart.yaml
  charts/tei/README.md
  charts/tei/ci/tei-mininum-values.yaml
  charts/tei/templates/_helpers.tpl
  charts/tei/templates/headless-service.yaml
  charts/tei/templates/service.yaml
  charts/tei/templates/serviceaccount.yaml
  charts/tei/templates/statefulset.yaml
  charts/tei/values.yaml
Labels: approved, ci-passed, lgtm, size/XL

#202 fix message queue config
  charts/milvus/Chart.yaml
  charts/milvus/templates/config.tpl
Labels: approved, ci-passed, size/XS

#203 feat: support empty dir for streaming node when message type if woodpecker
  charts/milvus/templates/streamingnode-deployment.yaml
Labels: approved, ci-passed, lgtm, size/XS

#206 feat: support security context
  charts/milvus/templates/attu-deployment.yaml
  charts/milvus/templates/datacoord-deployment.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-deployment.yaml
  charts/milvus/templates/indexnode-deployment.yaml
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-deployment.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-deployment.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/templates/streamingnode-deployment.yaml
  charts/milvus/values.yaml
  docs/security-context-configuration-guide.md
Labels: approved, ci-passed, lgtm, size/L
