Repository zilliztech/milvus-helm, pull requests merged in 2025-08, with the labels that each got.

#239 release tag 2.5.16
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XS

#241 refine milvus components for milvus 2.6
  charts/milvus/templates/_helpers.tpl
  charts/milvus/templates/config.tpl
  charts/milvus/templates/datacoord-svc.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-svc.yaml
  charts/milvus/templates/indexnode-hpa.yaml
  charts/milvus/templates/indexnode-svc.yaml
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-svc.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-svc.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/templates/streamingnode-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, size/L

#242 release tag 2.6.0 and update minio
  charts/milvus/Chart.yaml
  charts/milvus/README.md
  charts/milvus/templates/_helpers.tpl
  charts/milvus/templates/config.tpl
  charts/milvus/templates/datacoord-svc.yaml
  charts/milvus/templates/datanode-deployment.yaml
  charts/milvus/templates/indexcoord-svc.yaml
  charts/milvus/templates/indexnode-hpa.yaml
  charts/milvus/templates/indexnode-svc.yaml
  charts/milvus/templates/mixcoord-deployment.yaml
  charts/milvus/templates/proxy-deployment.yaml
  charts/milvus/templates/querycoord-svc.yaml
  charts/milvus/templates/querynode-deployment.yaml
  charts/milvus/templates/rootcoord-svc.yaml
  charts/milvus/templates/standalone-deployment.yaml
  charts/milvus/templates/streamingnode-deployment.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/XL

#244 update bitnami image to use legacy bitnami repo
  charts/milvus/Chart.yaml
  charts/milvus/values.yaml
Labels: approved, ci-passed, lgtm, size/S
